FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_SHOPIFY_APP_URL
ARG NEXT_PUBLIC_DEMO_STORE_ID=3
ARG NEXT_PUBLIC_STORE_NAME="Glow Beauty Co."
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_SHOPIFY_APP_URL=$NEXT_PUBLIC_SHOPIFY_APP_URL
ENV NEXT_PUBLIC_DEMO_STORE_ID=$NEXT_PUBLIC_DEMO_STORE_ID
ENV NEXT_PUBLIC_STORE_NAME=$NEXT_PUBLIC_STORE_NAME

RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

EXPOSE 3000

CMD ["npm", "start", "--", "-H", "0.0.0.0", "-p", "3000"]
